---
- name: Install the sudo package
  package:
    name: sudo
    state: present
  tags:
    - sudoers

- name: Validate and deploy the config file
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/sudocustom
    owner: root
    group: root
    mode: 0440
    validate: visudo -cf %s
  tags:
    - sudoers
